// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThrustSync.Data.Context;

#nullable disable

namespace TrustSync.Data.Migrations
{
    [DbContext(typeof(TrustSyncDbContext))]
    [Migration("20260610155333_AllowMultipleWorkOrdersPerApu")]
    partial class AllowMultipleWorkOrdersPerApu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThrustSync.Core.Models.APU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FailureCode")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartSerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefDes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RemovalIndicator")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("PartNumber");

                    b.HasIndex("PartSerialNumber");

                    b.HasIndex("RefDes");

                    b.HasIndex("RefDes", "PartNumber", "PartSerialNumber")
                        .IsUnique();

                    b.ToTable("APUs");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("ChangedOn");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.ExportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExportedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExportedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilterCriteria")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExportedBy");

                    b.HasIndex("ExportedOn");

                    b.ToTable("ExportLogs");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.KpiEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("EnteredOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FlightHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("OpTime")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnteredOn");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("KpiEntries");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.OracleSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PulledOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PulledOn");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("OracleSnapshots");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRACPR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HMC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JCN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastKpiUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MID")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OraclePulledOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TailNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApuId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("FRACPR");

                    b.HasIndex("JCN")
                        .IsUnique();

                    b.HasIndex("MID");

                    b.HasIndex("OraclePulledOn");

                    b.HasIndex("TailNumber");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.AuditLog", b =>
                {
                    b.HasOne("ThrustSync.Core.Models.WorkOrder", "WorkOrder")
                        .WithMany("AuditLogs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.KpiEntry", b =>
                {
                    b.HasOne("ThrustSync.Core.Models.WorkOrder", "WorkOrder")
                        .WithMany("KpiEntries")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.OracleSnapshot", b =>
                {
                    b.HasOne("ThrustSync.Core.Models.WorkOrder", "WorkOrder")
                        .WithOne("OracleSnapshot")
                        .HasForeignKey("ThrustSync.Core.Models.OracleSnapshot", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.WorkOrder", b =>
                {
                    b.HasOne("ThrustSync.Core.Models.APU", "APU")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ApuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("APU");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.APU", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ThrustSync.Core.Models.WorkOrder", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("KpiEntries");

                    b.Navigation("OracleSnapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
